{
    "name": "Custom Gonzalo Investments",
    "version": "18.0.1.0.0",
    "category": "Customizations",
    "author": "Gonzalo Crosio",
    "summary": "Custom reports for the client",
    "license": "AGPL-3",
    "application": False,
    "installable": True,
    "depends": [
        "mail",
    ],
    "data": [
        "security/ir.model.access.csv",
        "views/investment_transactions.xml",
        "views/investment_menu.xml",
        "views/investment_transactions_line.xml",
        "views/investment_purchase_mode.xml",
        "views/investment_location.xml",
        "views/investment_total.xml",
        "views/investment_assets.xml",
        "views/investments_api.xml",
        "views/investment_property.xml",
    ],
}
