{
    "name": "Custom Gonzalo Investments",
    "version": "19.0.1.0.0",
    "category": "Customizations",
    "author": "Gonzalo Crosio",
    "summary": "Custom reports for the client",
    "license": "AGPL-3",
    "application": False,
    "installable": True,
    "depends": [
        "mail",
        "base",
        "product",
        "account",
    ],
    "data": [
        "security/ir.model.access.csv",
        "views/crypto_holding.xml",
        "views/crypto_asset.xml",
        "views/crypto_sale_allocation.xml",
        "views/crypto_sale.xml",
        "views/crypto_purchase.xml",
        "views/crypto_purchase_mode.xml",
        "views/crypto_menus.xml",
    ],
}
