[options]
db_host = localhost
db_port = 5432
db_user = odoo
db_password = odoo
list_db = True
addons_path =
    /home/gonzalo/dev/personal/Odoo,
    /home/gonzalo/dev/_odoo-sources/odoo-19/addons,
dev_mode = reload,qweb,xml
log_level = info
admin_passwd = $pbkdf2-sha512$600000$MgZgbE1JifH.P4cwRiiF0A$ZX.yS63p257KZF92AzD.MZ2Fd7PBV/fQKf1KnutSB3NuowEvTq1a6QfnXF5FegNpODNkK59IckOh5xko.pcCaA

